baseURL: "http://www.whiteknife.in"
title: Rishabhdeep Singh
theme: zzo
defaultContentLanguage: en
defaultContentLanguageInSubdir: true
hasCJKLanguage: true
summaryLength: 70
buildFuture: true
copyright: "©{year}, All Rights Reserved"
timeout: 10000
enableEmoji: true
paginate: 13
rssLimit: 100
enableGitInfo: true
googleAnalytics: "G-X0RTH6PQW5"
markup:
  goldmark:
    renderer:
      hardWraps: true
      unsafe: true
      xHTML: true
  highlight:
    codeFences: true
    lineNos: true
    lineNumbersInTable: true
    noClasses: false
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
outputs:
  home:
    - HTML
    - RSS
    - JSON
taxonomies:
  category: categories
  tag: tags
  series: series

deployment:
  order:
    - .jpg$
    - .gif$
  targets:
    - name: whiteknife_website
      URL: "gs://whiteknife_website"
  matchers:
    - pattern: ^.+\.(js|css|svg|ttf)$
      cacheControl: "max-age=31536000, no-transform, public"
      gzip: true
    - pattern: ^.+\.(png|jpg)$
      cacheControl: "max-age=31536000, no-transform, public"
      gzip: false
    - pattern: ^sitemap\.xml$
      contentType: application/xml
      gzip: true
    - pattern: ^.+\.(html|xml|json)$
      gzip: true
