main:
  - identifier: writeups
    name: Writeups
    url: writeups
    weight: 1
  - identifier: posts
    name: Posts
    url: posts
    weight: 1
  - identifier: talks
    name: Talks
    url: talks
    weight: 2
  - identifier: about
    name: About
    url: about
    weight: 3
  - identifier: contact
    name: Contact
    url: contact
    weight: 4
  - parent: about
    name: About Me
    url: about
  - parent: about
    name: Resume
    url: resume.pdf
