main:
  - identifier: about
    name: About
    url: about
    weight: 1
  - identifier: archive
    name: Archive
    url: archive
    weight: 2
  - identifier: gallery
    name: Gallery
    url: gallery
    weight: 3
  - parent: gallery
    name: Cartoon
    url: gallery/cartoon
  - parent: gallery
    name: Photo
    url: gallery/photo
  - identifier: posts
    name: Posts
    url: posts
    weight: 4
  - identifier: notes
    name: Notes
    url: notes
    weight: 5
  - identifier: contact
    name: Contact
    url: contact
    weight: 6
  - identifier: resume
    name: Resume
    url: resume.pdf
    weight: 6
