main:
  - identifier: about
    name: About
    url: about
    weight: 1
  - identifier: posts
    name: Posts
    url: posts
    weight: 2
  - identifier: contact
    name: Contact
    url: contact
    weight: 3
  - identifier: resume
    name: Resume
    url: resume.pdf
    weight: 4
