logoText: IamWhiteKnife
logoType: short
logo: true
description: Rishabhdeep Singh's site.
custom_css:
  - css/font.css
custom_js: []
useFaviconGenerator: true
languagedir: ltr
themeOptions:
  - hacker
  - dark
  - kimbie
notAllowedTypesInHome:
  - contact
  - talks
  - about
  - showcase
notAllowedTypesInHomeSidebar:
  - about
  - archive
  - showcase
notAllowedTypesInArchive:
  - about
  - talks
  - showcase
notAllowedTypesInHomeFeed:
  - about
  - archive
  - contact
  - talks
  - showcase
  - publication
  - presentation
  - resume
  - gallery
enablePinnedPosts: true
viewportSize: wide
enableUiAnimation: true
hideSingleContentsWhenJSDisabled: false
minItemsToShowInTagCloud: 1
homeHeaderType: slide
showMobileMenuTerms:
  - tags
  - categories
  - series
enableThemeChange: true
enableBreadcrumb: true
enableSearch: true
enableSearchHighlight: true
enableAppbarSearchIcon: true
enableGoToTop: true
enableWhoami: true
summaryShape: classic
archiveGroupByDate: "2019"
archivePaginate: 13
paginateWindow: 2
talksPaginate: 7
talksGroupByDate: "2006"
myname: Rishabhdeep Singh
email: rishabhdeepsingh98@gmail.com
whoami: CTF Player | Algorithmist | Learner
bioImageUrl: images/my.jpeg
useGravatar: true
location: "Gurdaspur, Punjab"
organization: ""
link: "https://github.com/rishabhdeepsingh"
enableBio: true
enableBioImage: true
enableSidebar: true
enableSidebarTags: true
enableSidebarSeries: true
enableSidebarCategories: true
enableHomeSidebarTitles: true
enableListSidebarTitles: true
enableToc: true
hideToc: false
tocPosition: outer
tocFolding: false
enableTocSwitch: true
itemsPerCategory: 5
sidebarPosition: right
tocLevels:
  - h2
  - h3
  - h4
enableSidebarPostsByOrder: true
showPoweredBy: true
showFeedLinks: true
showSocialLinks: true
enableLangChange: false
googleTagManager: ""
baiduAnalytics: ""
enableBusuanzi: false
busuanziSiteUV: true
busuanziSitePV: true
busuanziPagePV: true
enableComment: true
disqus_shortname: ""
commento: false
gitment:
  owner: ""
  repo: ""
  clientId: ""
  clientSecret: ""
utterances:
  owner: ""
  repo: ""
  message: ""
  link: ""
gitalk:
  owner: ""
  repo: ""
  clientId: ""
  clientSecret: ""
isso:
  enable: false
  scriptSrc: ""
  dataAttrs: ""
socialOptions:
  email: "mailto:rishabhdeepsingh98@email.com"
  facebook: ""
  twitter: "https://twitter.com/rds_98"
  github: "https://github.com/rishabhdeepsingh"
  stack-overflow: "https://stackoverflow.com/users/8077496/rishabh-deep-singh"
  instagram: "https://instagram.com/rishabhdeepsingh"
  google-plus: ""
  youtube: ""
  medium: "https://medium.com/@rishabhdeepsingh"
  tumblr: ""
  linkedin: "https://www.linkedin.com/in/rishabhdeepsingh/"
  pinterest: ""
  stack-exchange: ""
  telegram: "https://t.me/iamwhiteknife"
  steam: "https://steamcommunity.com/id/IamWhiteKnife/"
  weibo: ""
  douban: ""
  csdn: ""
  gitlab: "https://gitlab.com/rishabhdeepsingh"
  mastodon: ""
  jianshu: ""
  zhihu: ""
  signal: ""
  matrix: ""
  xmpp: ""
  dev-to: "https://dev.to/rishabhdeepsingh"
  gitea: ""
  google-scholar: ""
  twitch: "https://www.twitch.tv/iamwhiteknife"
donationOptions:
  enable: true
  alipay: ""
  wechat: ""
  paypal: "https://paypal.me/RishabhdeepSingh?locale.x=en_GB"
  patreon: ""
  bitcoin: ""
copyrightOptions:
  enableCopyrightLink: false
  copyrightLink: ""
  copyrightLinkImage: ""
  copyrightLinkText: ""
share:
  - name: facebook
  - name: twitter
    username: rds_98
writtenTimeIcon: "📅"
modifiedTimeIcon: "📝"
readingTimeIcon: "☕"
authorIcon: "✍️"
pagePvIcon: "👀"
tagIcon: "🏷️"
publicationIcon: "📚"
typeIcon: "🎯"
